run:
  tests: true
  timeout: 10m
  skip-dirs:
    - internal/pb

linters-settings:
  errcheck:
    check-blank: false
    ignore: fmt:.*,[rR]ead|[wW]rite|[cC]lose,io:Copy
  gocritic:
    disabled-checks:
      - commentFormatting
  dupl:
    # tokens count to trigger issue, 150 by default
    threshold: 500
  decorder:
    dec-order:
      - type
      - const
      - var
      - func
    disable-dec-order-check: false

  revive:
    enable-all-rules: true
    rules:
      - name: cyclomatic
        disabled: true
      - name: argument-limit
        disabled: true
      - name: function-length
        disabled: true
      - name: function-result-limit
        disabled: true
      - name: line-length-limit
        disabled: true
      - name: file-header
        disabled: true
      - name: cognitive-complexity
        disabled: true
      - name: banned-characters
        disabled: true
      - name: max-public-structs
        disabled: true
      - name: add-constant
        disabled: true
      - name: unhandled-error
        disabled: true
      - name: deep-exit
        disabled: true
      - name: nested-structs
        disabled: true

linters:
  enable:
    - asciicheck
    - bodyclose
    - depguard
    - dupl
    - errcheck
    - gci
    - gocritic
    - gofmt
    - gosimple
    - govet
    - ineffassign
    - importas
    - misspell
    - nakedret
    - prealloc
    - revive
    - staticcheck
    - unconvert
    - unparam
    - unused
