package schema

import (
	"context"

	"github.com/jackc/pgx/v4"
	"github.com/stretchr/testify/mock"
)

// mockDatabase is an autogenerated mock type for the mockDatabase type
type mockDatabase struct {
	mock.Mock
}

// Delete provides a mock function with given fields: ctx, t, args
func (_m *mockDatabase) Delete(ctx context.Context, t *Table, args []interface{}) error {
	ret := _m.Called(ctx, t, args)

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, *Table, []interface{}) error); ok {
		r0 = rf(ctx, t, args)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// Exec provides a mock function with given fields: ctx, query, args
func (_m *mockDatabase) Exec(ctx context.Context, query string, args ...interface{}) error {
	var _ca []interface{}
	_ca = append(_ca, ctx, query)
	_ca = append(_ca, args...)
	ret := _m.Called(_ca...)

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, string, ...interface{}) error); ok {
		r0 = rf(ctx, query, args...)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// Insert provides a mock function with given fields: ctx, t, instance
func (_m *mockDatabase) Insert(ctx context.Context, t *Table, instance []*Resource) error {
	ret := _m.Called(ctx, t, instance)

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, *Table, []*Resource) error); ok {
		r0 = rf(ctx, t, instance)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// Query provides a mock function with given fields: ctx, query, args
func (_m *mockDatabase) Query(ctx context.Context, query string, args ...interface{}) (pgx.Rows, error) {
	var _ca []interface{}
	_ca = append(_ca, ctx, query)
	_ca = append(_ca, args...)
	ret := _m.Called(_ca...)

	var r0 pgx.Rows
	if rf, ok := ret.Get(0).(func(context.Context, string, ...interface{}) pgx.Rows); ok {
		r0 = rf(ctx, query, args...)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(pgx.Rows)
		}
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(context.Context, string, ...interface{}) error); ok {
		r1 = rf(ctx, query, args...)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// QueryOne provides a mock function with given fields: ctx, query, args
func (_m *mockDatabase) QueryOne(ctx context.Context, query string, args ...interface{}) pgx.Row {
	var _ca []interface{}
	_ca = append(_ca, ctx, query)
	_ca = append(_ca, args...)
	ret := _m.Called(_ca...)

	var r0 pgx.Row
	if rf, ok := ret.Get(0).(func(context.Context, string, ...interface{}) pgx.Row); ok {
		r0 = rf(ctx, query, args...)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(pgx.Row)
		}
	}

	return r0
}
