// Code generated by MockGen. DO NOT EDIT.
// Source: usage.go
//
// Generated by this command:
//
//	mockgen -package=mocks -destination=../premium/mocks/marketplacemetering.go -source=usage.go -exclude_interfaces=TokenClient,QuotaMonitor,UsageClient AWSMarketplaceClientInterface
//

// Package mocks is a generated GoMock package.
package mocks

import (
	context "context"
	reflect "reflect"

	marketplacemetering "github.com/aws/aws-sdk-go-v2/service/marketplacemetering"
	gomock "go.uber.org/mock/gomock"
)

// MockAWSMarketplaceClientInterface is a mock of AWSMarketplaceClientInterface interface.
type MockAWSMarketplaceClientInterface struct {
	ctrl     *gomock.Controller
	recorder *MockAWSMarketplaceClientInterfaceMockRecorder
	isgomock struct{}
}

// MockAWSMarketplaceClientInterfaceMockRecorder is the mock recorder for MockAWSMarketplaceClientInterface.
type MockAWSMarketplaceClientInterfaceMockRecorder struct {
	mock *MockAWSMarketplaceClientInterface
}

// NewMockAWSMarketplaceClientInterface creates a new mock instance.
func NewMockAWSMarketplaceClientInterface(ctrl *gomock.Controller) *MockAWSMarketplaceClientInterface {
	mock := &MockAWSMarketplaceClientInterface{ctrl: ctrl}
	mock.recorder = &MockAWSMarketplaceClientInterfaceMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockAWSMarketplaceClientInterface) EXPECT() *MockAWSMarketplaceClientInterfaceMockRecorder {
	return m.recorder
}

// MeterUsage mocks base method.
func (m *MockAWSMarketplaceClientInterface) MeterUsage(ctx context.Context, params *marketplacemetering.MeterUsageInput, optFns ...func(*marketplacemetering.Options)) (*marketplacemetering.MeterUsageOutput, error) {
	m.ctrl.T.Helper()
	varargs := []any{ctx, params}
	for _, a := range optFns {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "MeterUsage", varargs...)
	ret0, _ := ret[0].(*marketplacemetering.MeterUsageOutput)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// MeterUsage indicates an expected call of MeterUsage.
func (mr *MockAWSMarketplaceClientInterfaceMockRecorder) MeterUsage(ctx, params any, optFns ...any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	varargs := append([]any{ctx, params}, optFns...)
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "MeterUsage", reflect.TypeOf((*MockAWSMarketplaceClientInterface)(nil).MeterUsage), varargs...)
}
