name: Lint Markdown files

on:
  pull_request:
    paths:
      - ".github/workflow/lint_markdown.yml"
      - "**.md"

jobs:
  lint-grammar:
    runs-on: ubuntu-latest
    timeout-minutes: 10
    steps:
      - name: Git checkout
        uses: actions/checkout@v3
      - name: Vale
        uses: errata-ai/vale-action@v2
        with:
          vale_flags: "--glob=!{docs/testdata/*,CHANGELOG.md,.github/styles/proselint/README.md,examples/simple_plugin/docs/*.md}"
          filter_mode: nofilter
        env:
          GITHUB_TOKEN: ${{secrets.GITHUB_TOKEN}}
  lint-structure:
    runs-on: ubuntu-latest
    timeout-minutes: 10
    steps:
      - name: Git checkout
        uses: actions/checkout@v3
      - name: markdownlint-cli
        uses: nosborn/github-action-markdown-cli@v3.3.0
        with:
          files: .
          config_file: .markdownlint.yaml
          ignore_files: "{docs/testdata/*,CHANGELOG.md,examples/simple_plugin/docs/*.md}"
