name: Lint Markdown files

on:
  pull_request:
    paths:
      - ".github/workflow/lint_markdown.yml"
      - "*.md"

jobs:
  lint-grammar:
    runs-on: ubuntu-latest
    steps:
      - name: Git checkout
        uses: actions/checkout@v3
      - name: Vale
        uses: errata-ai/vale-action@v2
        with:
          vale_flags: "--glob='!{docs/.snapshots/*,CHANGELOG.md,.github/styles/proselint/README.md}'"
          filter_mode: nofilter
        env:
          GITHUB_TOKEN: ${{secrets.GITHUB_TOKEN}}
  lint-structure:
    runs-on: ubuntu-latest
    steps:
      - name: Git checkout
        uses: actions/checkout@v3
      - name: markdownlint-cli
        uses: nosborn/github-action-markdown-cli@v3.0.1
        with:
          files: .
          config_file: .markdownlint.yaml
          ignore_files: "CHANGELOG.md"
