name: Lint Markdown files

on:
  pull_request:
    paths:
      - ".github/workflow/lint_markdown.yml"
      - "**.md"

jobs:
  lint-grammar:
    runs-on: ubuntu-latest
    timeout-minutes: 10
    steps:
      - name: Git checkout
        uses: actions/checkout@v4
      - run: |
          venv="$HOME/.local/share/venv"
          python3 -m venv "$venv"
          echo "$venv/bin" >> $GITHUB_PATH
      - name: Vale
        uses: errata-ai/vale-action@dcded780f1ff68e2558e802a165a484a4a3e2fb8
        with:
          vale_flags: "--glob=!{docs/testdata/*,CHANGELOG.md,.github/styles/proselint/README.md,examples/simple_plugin/docs/*.md}"
          filter_mode: nofilter
          version: '3.0.3'
        env:
          GITHUB_TOKEN: ${{secrets.GITHUB_TOKEN}}
  lint-structure:
    runs-on: ubuntu-latest
    timeout-minutes: 10
    steps:
      - name: Git checkout
        uses: actions/checkout@v4
      - name: markdownlint-cli
        uses: nosborn/github-action-markdown-cli@v3.5.0
        with:
          files: .
          config_file: .markdownlint.yaml
          ignore_files: "{docs/testdata/*,CHANGELOG.md,examples/simple_plugin/docs/*.md}"
