name: release-please
on:
  push:
    branches:
      - main

permissions:
  contents: read

jobs:
  release-please:
    runs-on: ubuntu-latest
    timeout-minutes: 10
    steps:
      - name: Generate GitHub App token
        id: app-token
        uses: actions/create-github-app-token@1b10c78c7865c340bc4f6099eb2f838309f1e8c3 # v3
        with:
          app-id: ${{ secrets.CQ_APP_ID }}
          private-key: ${{ secrets.CQ_APP_PRIVATE_KEY }}
          permission-contents: write
          permission-pull-requests: write
      - uses: googleapis/release-please-action@45996ed1f6d02564a971a2fa1b5860e934307cf7 # v5
        id: release
        with:
          token: ${{ steps.app-token.outputs.token }}
      - name: Parse semver string
        if: steps.release.outputs.release_created
        id: semver_parser
        uses: booxmedialtd/ws-action-parse-semver@7784200024d6b3fc01253e617ec0168daf603de3
        with:
          input_string: ${{ steps.release.outputs.tag_name }}
      - name: Mark as pre-release
        if: steps.semver_parser.outputs.prerelease != ''
        uses: tubone24/update_release@1cfa79ccf7422570d9a9c6b6de749ff4b280e48b
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          TAG_NAME: ${{ steps.release.outputs.tag_name }}
        with:
          prerelease: true
      - name: Trigger Renovate
        uses: actions/github-script@3a2844b7e9c422d3c10d287c895573f7108da1b3 # v9
        if: steps.release.outputs.release_created && steps.semver_parser.outputs.prerelease == ''
        with:
          github-token: ${{ steps.app-token.outputs.token }}
          script: |
            github.rest.actions.createWorkflowDispatch({
              owner: 'cloudquery',
              repo: '.github',
              workflow_id: 'renovate.yml',
              ref: 'main',
            })
