name: "Unit tests"
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  unitests:
    strategy:
      matrix:
        os: [windows-latest, macos-latest]
    runs-on: ${{ matrix.os }}
    steps:
      - name: Check out code into the Go module directory
        uses: actions/checkout@v3
      - name: Set up Go 1.x
        uses: actions/setup-go@v3
        with:
          go-version-file: "go.mod"
          cache: true
      - run: go mod download
      - run: go build ./...
      - name: Run tests
        run: go test -short -race ./...